# General
GAME_NAME = "The Brick Breaker Game"
START_TIME = 0.0 # this will be set by main.py and will be updated by the Frame class
FRAME_COUNT = 0 # this will be updated by the Frame class
FRAME_COUNT_PER_LEVEL = 0
NO_OF_LIVES = 3 # Life count
SCORE = 0
PENALTY = 0
TOTAL_SCORE = 0
FALLING_BRICK_FRAME_NUMBER = 200
ACCELERATION_DUE_TO_GRAVITY = 4

# Frame
FRAME_HEIGHT = 30
FRAME_WIDTH = 80
SCORE_BOX_HEIGHT = 8
BOTTOM_EMPTY_SPACE = 3
INIT_FRAME_RATE = 24.0
FRAME_RATE = INIT_FRAME_RATE # 24 frames per second

# Paddle
PADDLE_WIDTH = 7
PADDLE_HEIGHT = 1
PADDLE_SHAPE = '|-----|' 
PADDLE_INITIAL_POS = [(FRAME_WIDTH-PADDLE_WIDTH)//2, FRAME_HEIGHT - BOTTOM_EMPTY_SPACE] # (X, Y) COORDINATES LEFT END OF PADDLE 

# Ball
BALL_WIDTH = 3 
BALL_SHAPE = '(O)' # SHAPE = '(O)'
BALL_INIT_VEL = [0, -1 * FRAME_RATE//2]  # (direction - north west wrt the screen (keyboard - south)) (vel_x, vel_y) No of frames per move
BALL_FAST_VEL = [0, -1 * FRAME_RATE]
BALL_INITIAL_POS = [PADDLE_INITIAL_POS[0] + (PADDLE_WIDTH - BALL_WIDTH)//2, PADDLE_INITIAL_POS[1] - 1] # (X, Y) LEFT END OF BALL

# Brick Width
BRICK_WIDTH = 5
BRICK_SHAPE = '{|||}'
RAINBOW_COLOR_CHANGE_RATE = 4 # implies once in every 12 frames

# Power ups
POWERUP_VEL = [0, FRAME_RATE//4] # (x, y)
POWERUP_WIDTH = 4
EP_POWERUP_SHAPE = '$EP$' # EXPAND PADDLE
SP_POWERUP_SHAPE = '$SP$' # SHRINK PADDLE
BM_POWERUP_SHAPE = '$BM$' # BALL MULTIPLIER
FB_POWERUP_SHAPE = '$FB$' # FAST BALL
TB_POWERUP_SHAPE = '$TB$' # THRU BALL
PG_POWERUP_SHAPE = '$PG$' # PADDLE GRAB
ShP_POWERUP_SHAPE = '$SH$' # SHOOTING PADDLE
POWERUP_TIMEPERIOD = 10 # in secs

# Bullets
BULLET_SHAPE = '8'
BULLET_WIDTH = 1

# Boss
BOSS_SHAPE = 'U---F---O'
BOSS_WIDTH = 9
BOSS_HEIGHT = 1
BOSS_INIT_POSITION = [(FRAME_WIDTH-PADDLE_WIDTH)//2, 1]
BOSS_VEL = 4
BOSS_INITIAL_HEALTH = 8

# Bombs
BOMB_SHAPE = 'D'
BOMB_WIDTH = 1
BOMB_RELEASE_PROBABILITY = 0.02